name: "hacs"
on:
  push:
  pull_request:

jobs:
  validate:
    name: "validate"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"




